<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Comments.aspx.cs" Inherits="ConsultantJobPortal.Comments" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
<h3>
    Comments
</h3>

<p>
</p>

<div>
      Stream:
        <asp:Label ID="lblStream" runat="server"></asp:Label>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
        <br />
        Status:
        <asp:Label ID="lblStatus" runat="server"></asp:Label>
        <br />
        <br />
        Company:
        <asp:Label ID="lblCompany" runat="server"></asp:Label>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <br />
        <br />
        Location:
        <asp:Label ID="lblLocation" runat="server"></asp:Label>
        <br />
        <br />
        Title:
        <asp:Label ID="lblTitle" runat="server"></asp:Label>
        <br />
        <br />
        Description:<br />
        <asp:Label ID="lblDescription" runat="server"></asp:Label>
        <br />
        <br />
        Skills:
        <asp:BulletedList ID="blSkills" runat="server">
        </asp:BulletedList>
        <br />
        <br />
        DatePosted:
        <asp:Label ID="lblDateposted" runat="server"></asp:Label>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Deadline:
        <asp:Label ID="lblDeadline" runat="server"></asp:Label>
        <br />
        <br />
        Account Manager:
        <asp:Label ID="lblAccMan" runat="server"></asp:Label>
        <br />
      <br />
        <asp:LinkButton ID="LinkButton1" runat="server" onclick="LinkButton1_Click">Add Comment</asp:LinkButton>
        <br />
        <br />
        <asp:Panel ID="pnlAddCom" runat="server" BackColor="AliceBlue" Height="223px" 
            Visible="False">
            <br />
            &nbsp;Comment:<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="txtComment" runat="server" Height="107px" TextMode="MultiLine" 
                Width="804px" Rows="10"></asp:TextBox>
            <br />
            <br />
            <asp:Button ID="btnAdd" runat="server" onclick="btnAdd_Click" Text="Add" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnCancel" runat="server" Text="Cancel" 
                onclick="btnCancel_Click" />
        </asp:Panel>
        <br />
        <asp:Label ID="lblSuccess" runat="server" Text="" 
            CssClass="successNotification"></asp:Label>
        <asp:Label ID="lblError" runat="server" Text="" 
          CssClass="failureNotification"></asp:Label>
        <br />
</div>
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
    <ContentTemplate>
        <asp:Timer ID="cmntTimer" runat="server" Interval="1000" OnTick="cmntTimer_tick"></asp:Timer>
        <br />
        <asp:GridView ID="gvComments" runat="server"
                      ShowHeader="false" CellPadding="20"
                      GridLines="None" HorizontalAlign="Center"
                      AllowPaging="true" PageSize="20"
                      AutoGenerateDeleteButton="true" 
                      onrowdeleting="gvComments_RowDeleting">
            <AlternatingRowStyle BackColor="AliceBlue" ForeColor="Black" />
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="CornflowerBlue" Font-Bold="true" ForeColor="GhostWhite" />
            <HeaderStyle BackColor="CornflowerBlue" Font-Bold="true" ForeColor="GhostWhite" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="GhostWhite" ForeColor="Black"/>
            <SelectedRowStyle BackColor="#B2D1B2" Font-Bold="true" ForeColor="GhostWhite" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>
    </ContentTemplate>
    </asp:UpdatePanel>


</asp:Content>